# 1. 파이썬을 강제로 설치해라!
[phases.setup]
nixPkgs = ["python3", "python311Packages.pip"]

# 2. 라이브러리 설치할 때 server 폴더로 들어가서 해라!
[phases.install]
cmds = ["cd server && pip install -r requirements.txt"]

# 3. 실행할 때도 server 폴더로 들어가서 파이썬으로 켜라!
[start]
cmd = "cd server && python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT"